/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-ui/lib/alert')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElButtonGroup: typeof import('element-ui/lib/button-group')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElCollapse: typeof import('element-ui/lib/collapse')['default']
    ElCollapseItem: typeof import('element-ui/lib/collapse-item')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTabPane: typeof import('element-ui/lib/tab-pane')['default']
    ElTabs: typeof import('element-ui/lib/tabs')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
